### ISSUE TITLE
Can recombination/mutation ratio be affected by within-species diversity?

### ISSUE THREAD

**Issue by megaptera-helvetiae** [xavierdidelot/ClonalFrameML#100]
Hola Xavier! 

We successfully used ClonalFrameML on our dataset and have already spent some days staring at the results and discussing them wildly during zoom meetings.

Now we are wondering whether we can get excited about the results or whether we have to stay cautious?!

We compared recombination/mutation ratios of three different endosymbiont bacterial species. The numbers turned out very different. However, I must say that one of the species is globally distributed and the strains that made it into the analysis are more different to each other than the other two species, which occur only locally and may have more closely related strains. 

I was thinking that by using recombination/mutation ratios we should be safe since both values are affected by strain diversity and therefore, taking a ratio is like normalizing for that.

What factors will affect the estimates of ratios of recombination/mutation events in ClonalFrameML?

I read that it will underestimate the ratio if the strains within a species are very diverse. In our case, the ratio is higher for the more diverse species (the global one). 

Are there any additional safety checks we could do to make sure our values are not just a reflection of the strain diversity and/or strain relatedness within each species but instead a real biological thing of increased recombination events?

Thanks in advance.

Laetitia

**Comment by xavierdidelot** [comment]
Hi Laetitia,

r/m is indeed the most robust statistic to use when comparing groups, compared to R/theta for example. r/m is the ratio of effects of recombination and mutation, whereas R/theta is the ratio of frequency of recombination and mutation. R/theta is harder to estimate because some recombination events have little effect, and so are hard to detect, and these events count just as much as others for R/theta but not as much for r/m.

It is harder for ClonalFrameML to detect recombination coming from within the population under study than recombination coming from external sources. So I would expect r/m to be more underestimated for more diverse populations than for less diverse ones. 

If you found that r/m is higher for the more diverse population then your observation goes against this expected bias, and you can be confident that there really is a greater effect of recombination in your more diverse population.

Best wishes,
Xavier

**Comment by megaptera-helvetiae** [comment]
Thank you! So we are still excited...
