### ISSUE TITLE
Events spanning multiple genes

### ISSUE THREAD

**Issue by annecmg** [xavierdidelot/ClonalFrameML#101]
I have converted core gene alignments to xmfa for ClonalFrameML. Since the genes are in an arbitrary order I did not expect events spanning multiple genes. However I find very long events. e.g. on node NC_018693 from 1 to 16937 which spans 8 genes and ends in the 9th. Now I am worried that the order of the gene alignment in the xmfa might influence the r/m estimation and the inference of genes under recombination. Has this been investigated? Can the long events spanning multiple genes be taken as evidence for each of these genes experiencing recombination?
Thanks for your help!

[core_genes2.cfml.cfml.pdf](https://github.com/xavierdidelot/ClonalFrameML/files/4862813/core_genes2.cfml.cfml.pdf)

**Comment by xavierdidelot** [comment]
Hello Anne,

Input xmfa files are dealt with by buffers between the genes, which are 1000bp of meaningless characters. Usually recombination events are short enough on average that you should not see often a recombination event that spans over a whole buffer and stretch over several genes. When it does happen, you can see it as evidence that each of the genes has been recombined. In the figure you sent I think it happens only for relatively long branches of the tree (like the one you mentioned leading to NC_018693) in which case there is quite a high probability that recombination happened anywhere on the genome. The value of r/m should not be significantly affected. If at all possible, it would be better to use a fasta file as input instead of a xmfa file, for example the result of mapping your genomes to a reference.

See also this issue: https://github.com/xavierdidelot/ClonalFrameML/issues/98

Best wishes,
Xavier

**Comment by annecmg** [comment]
Thank you, Xavier. I would like to continue with the core gene alignment and I understand now better how to interpret the results!
