### ISSUE TITLE
Using ClonaFrameML for populations of MAGs

### ISSUE THREAD

**Issue by megaptera-helvetiae** [xavierdidelot/ClonalFrameML#105]
Hi Xavier!

I am wondering whether we can use ClonalFrameML to calculate recombination to mutation rates of metagenome-assembled genomes (MAGs). I see that in the literature, people mostly used your tool on datasets of isolates. Would it be OK to use it on MAGs as well? Or would we have to de-convolute strains within our MAGs first?

MAGs are usually a mix of different strains/isolates and that might affect the results of ClonalFrameML.

Thanks!
Laetitia

**Comment by xavierdidelot** [comment]
Hi Laetitia,

The idea to use MAGs as input seems a bit risky. The ClonalFrame model assumes that there is a well-defined genealogy called the clonal genealogy which represents how the samples are related if there had been no recombination. With MAGs this assumption does not really hold, since as you wrote each MAG is likely to be a mixture. That being said, it is possible that even if the model does not really hold true the results might still tell you something interesting, in the same way as many statistical methods can give useful outputs even when we know that the reality is more complex than assumed by the method. So you might still want to give this a try, but I can't promise that the results will be very meaningful!

Best wishes,
Xavier
