### ISSUE TITLE
ClonalFrameML not producing all outputs.

### ISSUE THREAD

**Issue by izakbed** [xavierdidelot/ClonalFrameML#106]
Hi! My name is Isaac! Thanks for the interesting software that I want to use for my pipeline. 

However when I run the command nohup ClonalFrameML "/home/ibedard/core_genome_concat_90/RAxML_tree.nwk" "/home/ibedard/core_genome_concat_90/Concatenated_Alignment.fasta" Campy.output -emsim 100 -embranch true -embranch_dispersion 0.1 -show_progress TRUE -imputation_only FALSE > Campy.log.txt  &

The ClonalFrameML program seems to run until cross reference and ML sequence are produced but no tree or emsim.txt are produced? Any idea what is causing this issue?

Best,
Isaac

**Comment by izakbed** [comment]
After using the test data it seems as though it is a problem with my data set as the analysis just seems to stop after this step 

Wrote imputed and reconstructed ancestral states to Campy.output.ML_sequence.fasta
Wrote position cross-reference file to Campy.output.position_cross_reference.txt

Could it be a problem with the missing data? I am currently using a dash for missing loci.

**Comment by xavierdidelot** [comment]
Hi Isaac,

ClonalFrameML can deal well with missing data so this is probably not the problem here. What happens if you try without any optional arguments, so using the following command line:

`nohup ClonalFrameML "/home/ibedard/core_genome_concat_90/RAxML_tree.nwk" "/home/ibedard/core_genome_concat_90/Concatenated_Alignment.fasta" Campy.output  > Campy.log.txt &`

Does this generate the corrected tree file? If not it's a problem with your data itself, but if yes you could try to see which of the options is causing the issue.

Best wishes,
Xavier

**Comment by izakbed** [comment]
Hi Xavier,

Thanks for the help. I fixed the issue by reducing the size of the alignment to only include SNPs. However, when I tried to run the Rscript I got this error. 

Rscript cfml_results_2.R Campy.output
Error in file(filename, "r", encoding = encoding) :
  cannot open the connection
Calls: source -> file
In addition: Warning message:
In file(filename, "r", encoding = encoding) :
  cannot open file '/home/wilson/R/myutils/fasta.R': No such file or directory
Execution halted
 

Any idea what is happening here? I just downloaded both R packages today so I am sure that they are functional. 

Thanks,
Isaac

**Comment by xavierdidelot** [comment]
Hi Isaac,

You should not run ClonalFrameML on an alignment of SNPs only, because the distance between SNPs is important to determine when recombination events happened.

Concerning the R script, make sure to use the version at https://github.com/xavierdidelot/ClonalFrameML/blob/master/src/cfml_results.R

Best wishes,
Xavier
