### ISSUE TITLE
xmfa format question; error: Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by agor0** [xavierdidelot/ClonalFrameML#121]
I am trying to run ClonalFrameML using an xmfa input file and am getting the error "Segmentation fault (core dumped)". I tried running using a single large lcb that contained sequences for all strains present in the newick file and it ran successfully. The complete xmfa file contains lcbs that do not have sequences for each strain, and I'm wondering if this is supported by ClonalFrameML or might be what is causing the problem?

Thank you in advance!

**Comment by xavierdidelot** [comment]
The input file needs to have all blocks containing all sequences. Since you have blocks with missing sequences, you could get a valid input file by either remove these blocks, or add the sequences into these blocks using gaps (N or - characters) only. The first solution is preferable if you have many sequences missing in a block and you want to focus more on the core, the second solution is preferable if you have only a few sequences missing in a block and you really want to analyse these blocks.
