### ISSUE TITLE
convert_NewickTree_to_marginal_tree()

### ISSUE THREAD

**Issue by ga23981** [xavierdidelot/ClonalFrameML#124]
Hello Xavier,

I am stuck with the following error while using clonalFrameML:

ClonalFrameML parsnp_mod.nwk parsnp_mod.mfa out -emsim 100 > out.log.txt

ClonalFrameML 
emsim = 100
Finished reading in control file.

Read 17 sequences of length 79464 sites from parsnp_mod.mfa
**ERROR: convert_NewickTree_to_marginal_tree(): Number of descendant nodes (3) incompatible with a strictly bifurcating rooted tree**

Please see the newick tree file that I am using:
(('PANS_07_14':0.00395088,('PANS_99_15':0.00366452,('PANS_07_10':9.94983e-07,'PANS_07_12':1.98997e-06)1:0.00384899)1:0.000618282)1:0.000568633,(('PNA_15_2':0.00413694,('NCPPB2282':0,'NCPPB1562':1.98997e-07)1:0.00440021)1:0.000377696,(('PNA_03_3':0.00397217,('NCPPB2275':9.94983e-07,'NCPPB1877':7.95986e-07)1:0.00386193)1:0.000519978,(('PANS_07_6':9.15384e-06,'PANS_07_4':7.16388e-06)1:0.00419147,(('PNA_14_9':0,'PNA_14_11':0,'PNA_14_12':0):0.00145486,('NCPPB2281':1.59197e-06,'LMG2632':1.03478e-05)1:0.00149267)1:0.00252706)1:0.000377895):0.000355806)1:0.000103577)1:0;

**Comment by ga23981** [comment]
I checked for the spaces in the header of fasta file.

**Comment by xavierdidelot** [comment]
ClonalFrameML does not allow multichotomies in the input tree (except for the root which is allowed to have three descendants since the tree is seen as unrooted). 
In your tree you have a multichotomy here: 
('PNA_14_9':0,'PNA_14_11':0,'PNA_14_12':0)
You could resolve this for example using the "multi2di" command of the R package ape.
