### ISSUE TITLE
segmentation fault (core dumped)

### ISSUE THREAD

**Issue by annarerra** [xavierdidelot/ClonalFrameML#130]
Hello,

I try to run clonalframeml with slurm or without and i have a segmenation fault (core dumped) error.
My command is:
_software-run clonalframeml-v1.12 ClonalFrameML RAxML_bipartitions.raxmlout core_gene_alignment.aln raxml.output -emsim 50 -xmfa_file true_

The input alignment is coming from roary, it is a multifasta basically, so i used the "-xmfa_file true" option.
You think the error is coming from clonalframeml or from memory/right/other  issues?

Thank you in advance :)

**Comment by xavierdidelot** [comment]
Your command line looks fine and unless your datasets contains thousands of genomes it's unlikely to be an issue with memory. I think the problem is most likely to be that the input files are not formatted exactly as expected by ClonalFrameML. You could check if the tree has exactly the same leaf labels as the headers in the xmfa file. You could also try running with just the first fragments from the xmfa file. If that does not work and you can't see why not, you could send me by email your tree and the first xmfa fragment so I can investigate.
