### ISSUE TITLE
how to estimates of recombinations and mutations occurring in each strain

### ISSUE THREAD

**Issue by viviennelovely** [xavierdidelot/ClonalFrameML#19]
Dear Xavier/Daniel,
I want to estimates of recombinations and mutations occurring in each strain. I followed your user guide and got the results. I got R/theta, 1/delta, nu and M for each strain and node. For strain 1, r/m=R/theta× delta×nu=0.0535089×(1/2.20429)×5.99138, is that right? Why the delta is so small?
Would you please help me about this? Waiting for your help. Thank you very much.
Parameter	Branch	Posterior Mean	Posterior Variance	a_post	b_post
R/theta	Mean	1.30403	NA	NA	NA
1/delta	Mean	0.00838315	NA	NA	NA
nu	Mean	0.0410816	NA	NA	NA
M	Mean	0.00358976	NA	NA	NA
R/theta	1	0.0535089	3.07841e-05	93.0091	1738.2
1/delta	1	2.20429	0.0522412	93.0091	42.1945
nu	1	5.99138	0.035712	1005.17	167.769
M	1	0.255673	4.92296e-05	1327.83	5193.48
R/theta	2	3.0759	0.00175824	5381.04	1749.42
1/delta	2	0.552766	5.67901e-05	5380.34	9733.49
nu	2	3.27466	6.87087e-05	156070	47660
M	2	1.29058	0.00123671	1346.78	1043.55

Best wishes,
vivienne

**Comment by xavierdidelot** [comment]
Hi Danny,

I'm not sure what to reply to Vivienne's question about CFML, cf below.
This also happens in the exemplar Staph dataset, we get some per-branch
values of delta that are around 1 (eg between 0.5 and 2) and values of nu
also around 1, does it mean that no recombination was found on the branch?

Best wishes,
Xavier

**Comment by xavierdidelot** [comment]
Hi Vivienne,

I must admit I'm not completely sure about this, because I usually use the em option, not embranch. I think this probably happens only for branches where there is in fact no recombination detected, so that the values of delta (length of recombinant fragments) and nu (diversity in recombinant fragments) become irrelevant and can take any value. In such a situation, calculating r/m using the formula you indicate could be very misleading. Sorry I can't be more precise about this, I'll try to find out more about this and will let you know if find anything new.

Best wishes,
Xavier

**Comment by viviennelovely** [comment]
Dear Xavier，

Thank you very much for your rapid reply. If I use the em option, how can I calculate the r/m for each strain? I think that the r/m for each branch represent the r/m for each strain? Is that right ? If it is a misunderstanding, would you please tell me how to calculate the r/m for each strain? Thank you again for your help.

Best wishes,

Vivienne

 

发件人: bounces+848413-9595-zhangzw=big.ac.cn@sgmail.github.com [mailto:bounces+848413-9595-zhangzw=big.ac.cn@sgmail.github.com] 代表 Xavier Didelot
发送时间: 2015年10月27日 23:41
收件人: xavierdidelot/ClonalFrameML
抄送: viviennelovely
主题: Re: [ClonalFrameML] how to estimates of recombinations and mutations occurring in each strain (#19)

 

Hi Vivienne,

I must admit I'm not completely sure about this, because I usually use the em option, not embranch. I think this probably happens only for branches where there is in fact no recombination detected, so that the values of delta (length of recombinant fragments) and nu (diversity in recombinant fragments) become irrelevant and can take any value. In such a situation, calculating r/m using the formula you indicate could be very misleading. Sorry I can't be more precise about this, I'll try to find out more about this and will let you know if find anything new.

Best wishes,
Xavier

**Comment by xavierdidelot** [comment]
Dear Vivienne,

Please ignore my previous answer to this issue which was incorrect (sorry!). The correct answer is that the values reported in this file are factors that need to be multiplied with the means of the parameters (given in the top four lines) in order to get the per-branch values. After doing this, you should be able to calculate r/m values for each branch using the formula you mentioned.

Best wishes,
Xavier

**Comment by PaulineGachanja** [comment]
Hi @xavierdidelot @danny-wilson,
I have a similar output. I want to calculate the r/m for all my strains, not strain-wise. Is it okay to proceed even when we have NA values for the posterior variance, a_post and b_post? 
In this case, I will calculate r/m= (2.34805*1/0.0104088* 0.116572 )
Parameter       Branch  Posterior Mean  Posterior Variance      a_post  b_post
R/theta Mean    2.34805 NA      NA      NA
1/delta Mean    0.0104088       NA      NA      NA
nu      Mean    0.116572        NA      NA      NA
M       Mean    0.000327348     NA      NA      NA
R/theta 10B     1.14504 0.0327504       40.0336 34.9626
1/delta 10B     0.988396        0.0250165       39.0513 39.5098
nu      10B     1.17688 0.00345528      400.851 340.604
M       10B     1.05182 0.0523097       21.1494 20.1075

**Comment by xavierdidelot** [comment]
Hi Pauline,
Yes you can safely ignore the NA values for this calculation.
Best wishes,
Xavier
