### ISSUE TITLE
-ignore_user_sites,how to treat these region?

### ISSUE THREAD

**Issue by YangChaoCN** [xavierdidelot/ClonalFrameML#31]
Dear Xavier/Daniel,

I want to know the exact meaning of -ignore_user_sites,  is the region ignored involved in subsequent analysis or not ?

If the region is discarded, is there any difference between an alignment which the region is striped and an alignment with the  -ignore_user_sites option?

You recommend that we should extract the core from the file generated with mauve, is this means that I had better use core genome sequence alignment, not the complete genome sequence alignment with  -ignore_user_sites option to ignore non-core sites ?

Best wishes,
YangChao

**Comment by xavierdidelot** [comment]
Dear YangChao,

Ignoring a region via the "-ignore_user_sites" option is not the same thing as removing the region from your input file. The difference is that if you removed the region from your input file, the two flanking regions would become attached in the input, so that linkage would considered high between them and recombination events would be likely to stretch across them. When you ignore a region using "ignore_user_sites", the linkage between the flanks is kept consistent with the length of the ignored region. So for example if the ignore region is very large, linkage will be low between the flanks and a recombination event will not be allowed to stretch across the ignored region. So the results will be more biologically meaningful. The output files are also easier to interpret, since the location of sites in the output is the same as the location of sites in the input, no matter which sites were ignored.

If you work with Mauve, I would recommend first to extract the core regions using the stripSubsetLCBs utility, and then use the resulting xmfa file as an xmfa input into ClonalFrameML, which requires to use the "-xmfa_file true" option but not the "ignore_user_sites" option.

Best wishes,
Xavier

**Comment by YangChaoCN** [comment]
Thank you so much for your help!
