### ISSUE TITLE
Parameter 1/delta too small

### ISSUE THREAD

**Issue by YangChaoCN** [xavierdidelot/ClonalFrameML#36]
Dear Xavier,

when using CFML with my subject, I got the Parameter like that: R/theta 0.0925738, 1/delta 0.000199615 , nu      0.0143449, it seems that 1/delta was too small, this is abnormal. Could you tell me what factors may lead to a very small 1/delta? 

-kappa 3.62 -emsim 100 -ignore_user_sites xxx was used for the analysis.

Best regards, 
Yangchao

**Comment by xavierdidelot** [comment]
Dear YangChao,

If 1/delta is 0.000199615 then it means that on average the recombination events are of length 5009bp. This is not biologically unrealistic, it depends on your organism. One thing that could contribute to underestimating 1/delta and therefore overestimating delta is if your input is an xmfa file made of a lots of short regions, so that few actual recombination boundaries are seen in the dataset.

Best wishes,
Xavier
