### ISSUE TITLE
Distinguish recombination from other potential causes

### ISSUE THREAD

**Issue by YangChaoCN** [xavierdidelot/ClonalFrameML#37]
Hi Xavier,

In some recombination detection softwares such as  Gubbin which identifies loci containing elevated densities of base substitutions, they can't distinguish elevated densities of polymorphisms arising through
recombination from other potential causes such as mutational ‘hotspots’, or regions under relaxed or positive selection, on branches representing long periods of divergence.

In my opinion, there is no such biases in  ClonalFrameML, am I right?

Best wishes,
Yangchao

**Comment by xavierdidelot** [comment]
I'm afraid that is not completely correct. ClonalFrameML may be more robust than some other approaches because it is based on an explicit evolutionary model, but to some extent it is impossible that some other evolutionary process than recombination will be misinterpreted as recombination if it leaves a very similar or identical signature in the data. For example if a mutational hotspot happened in a given region and a given branch of the tree, it will probably be called a recombination.

**Comment by YangChaoCN** [comment]
Thank you!
