### ISSUE TITLE
Segmentation fault: 11

### ISSUE THREAD

**Issue by mmrec** [xavierdidelot/ClonalFrameML#41]
While using XMFA file I get message: "Segmentation fault: 11".

> ./ClonalFrameML mauve.guide_tree mauve_align mauve_out -xmfa_file true
> ClonalFrameML v1.0-19-g9488a80
> xmfa_file = true
> Finished reading in control file.
> 
> Read 24 sequences of length 6594565 sites from mauve_align
> Segmentation fault: 11

What does it mean?

Thanks in advance!

**Comment by xavierdidelot** [comment]
Dear mmrec,

This problem is probably caused by your tree not being exactly in the format expected by ClonalFrameML. 

You should check that the headers of your xmfa file correspond exactly to the name of the genomes in the tree file. So for example if you have a genome called "1" it needs to be called exactly that in both alignment (with header lines looking like "> 1") and in the tree file.

By the way, I see you are using the mauve guide tree as input, I'm not sure this will be a good enough tree, I would recommend building a tree from the alignment using a standard phylogenetic method (eg phyml or raxml) to use as input.

Also, if there is significant variation in genomic content between your genomes, you might need to extract the core of your mauve alignment before applying CFML, unless you have already done this of course.

Best wishes,
Xavier

**Comment by tseemann** [comment]
@xavierdidelot it would be good if you could get the input file from @mmrec and identify the source of the segmentation fault, and add a check to prevent this in future?
