### ISSUE TITLE
Confusion over version numbering

### ISSUE THREAD

**Issue by tseemann** [xavierdidelot/ClonalFrameML#45]
* I currently have a binary which says `1.7`
* I downloaded binary today and it says `1.25`
* The latest github code release  says `1.0`

Is 1.25 newer than 1.7 ?

What version of binary does the 1.0 github release source code correspond to?

**Comment by xavierdidelot** [comment]
Sorry for the confusion, this is because originally ClonalFrameML was hosted on google code using svn to keep track of version numbers, and this stopped working when moving over to github and git. The 1.7 and 1.25 versions are old from google code. The newer versions from github are all labeled 1.0-xxx where xxx is the number of commits since switching to github. For example the absolute latest version from github is 1.0-19. Hopefully everything will become clear once version 2 is released!
