### ISSUE TITLE
Interpretation of tree.newick scale bar

### ISSUE THREAD

**Issue by cahlstrom** [xavierdidelot/ClonalFrameML#61]
Hi there,
I understand that the branch lengths take into account both mutation and recombination events. I'm therefore unsure of how to reference the scale bar when I present the output tree - it's not strictly the number of substitutions per site and the number of recombination events is not quantified in this way. Would the following be the most accurate way to describe the scale bar?:
The scale bar represents the number of substitution events per site, scaled to reflect recombination events.

Cheers!
Christina

**Comment by xavierdidelot** [comment]
Dear Christina,

It's best to say that the scale bar represents the "number of mutations per site", or "expected number of mutations per site" if you want to be more precise. "substitutions per site" is not quite right because of the way recombination is being treated. Adding "scaled to reflect recombination events" is better, but may still be a bit confusing. Cf also page 6 of the Didelot and Wilson 2015 ClonalFrameML paper.

Best wishes,
Xavier
