### ISSUE TITLE
Multifurcation in ClonalFrameML tree!

### ISSUE THREAD

**Issue by mmaesaar** [xavierdidelot/ClonalFrameML#63]
I have an questio - why there are sometime multifurcations in ClonalFrameML tree. Is there a way to resolve them?

Thank you!

**Comment by xavierdidelot** [comment]
There shouldn't be any multifurcation in the ClonalFrameML output tree. In fact it checks that there aren't any in the input tree, and then the output tree has exactly the same topology as the input tree, so this really shouldn't happen. Maybe you are opening your output tree with something that automatically removes very short branches and turns them into multifurcations? Or maybe you are using the old ClonalFrame rather than the new ClonalFrameML?
