### ISSUE TITLE
questions about the output files

### ISSUE THREAD

**Issue by zhaoxvwahaha** [xavierdidelot/ClonalFrameML#72]
1. prefix.ML_sequence.fasta
The sequences in this file are sites which the recombination region is already removed? If not ,what can I do using this file?
2. I noticed that maskrc-svg could mask the recombination region to symbol "?", so should I remove these regions in all isolates and then do the subsequent analysis using the remaining sites, such as construct the tree, calculate genetic distance... ?
3. Is prefix.labelled_tree.newick generated using the prefix.ML_sequence.fasta? Is this tree already removing the recombination effect?

**Comment by xavierdidelot** [comment]
1. No, the prefix.ML_sequence.fasta is not an alignment of recombination-free sites. For the correct interpretation, see https://github.com/xavierdidelot/ClonalFrameML/wiki
2. It would be better to use the tree output by ClonalFrameML rather than recreate a tree based on recombination-free sites. See for example https://www.biorxiv.org/content/early/2018/06/14/347385
3. Yes, the prefix.labelled_tree.newick is the best estimate of the tree, after accounting for recombination.
