### ISSUE TITLE
-ignore_user_sites list of NON-CORE sites

### ISSUE THREAD

**Issue by ahmedmagds** [xavierdidelot/ClonalFrameML#74]
I use snippy from @tseemann to produce my clean.full.aln file that has ATGCN or - for gaps.
Is there a way to produce a list of non-core sites from this snippy output file so I can use it in CFML with the ignore_user_sites option?
Also What If I do not use this option, how this affects CFML results?
Thanks!

**Comment by ahmedmagds** [comment]
I coded a script to do the task

**Comment by matthieu-haudiquet** [comment]
Hi @ahmedmagds , did it work well with this method ? Any chance you posted the script somewhere?

**Comment by xavierdidelot** [comment]
For information, I do not recommend using the -ignore_user_sites option, unless you have a good reason for wanting to do this. CFML is able to deal with non-core sites using imputation, and so you should only use this option for example if you want to mask regions that you believe are not following the evolutionary model implemented in CFML.

**Comment by ahmedmagds** [comment]
@xavierdidelot Previously in this post, you recommended not to use -ignore_user_sites while in the real-world example you are using it (-ignore_user_sites Saureus.non-core-sites.txt).  It is bit confusing. I am working also on S. aureus dataset so can you elaborate more on this point please.

**Comment by xavierdidelot** [comment]
My recommendation is to use the -ignore_user_sites option only if you have a good reason for doing so. For example if you know that a genomic region is highly atypical and you want to exclude it from analysis. You might also want to exclude regions that are missing from a high proportion of the genomes, although excluding them will probably not make much difference compared to keeping them with gaps in the alignment due to the way ClonalFrameML deals with such gaps by imputation using maximum likelihood. If you want to be sure what the effect of -ignore_user_sites is on a specific analysis I would also suggest running ClonalFrameML both with and without this argument and compare the results.
