### ISSUE TITLE
Prior SD greater than Prior Mean

### ISSUE THREAD

**Issue by cizydorczyk** [xavierdidelot/ClonalFrameML#75]
Hello,

When setting the mean branch length prior, I would also like to set the branch length standard deviation. In the guidelines, it suggests that setting an SD appreciably greater than the mean is not advised...why might this be? What would be considered appreciably greater in this case? Would something like SD ~3X > than the mean be a problem?

Any help in understanding this would be greatly appreciated. While I am not overly familiar with the intricacies of these types of analyses, I would like to learn!

Thank you,
Conrad Izydorczyk

**Comment by xavierdidelot** [comment]
Hello Conrad,

The default prior for branch lengths should work for most analyses. You can change both the mean and the standard deviation of this prior, but I can't think of many situations where you would really have good reasons for doing this. The main requirement is to make sure that your prior is uninformative, since it seems unlikely that you have any prior information on branch lengths before looking at the sequences. If you use anything other than the default setting, for example a prior where standard deviation equal to 3x the mean as you suggested, and you find that it makes a significant difference compared to the default prior, then you should think carefully about what it means and if you had good reasons for this prior choice. 

Best wishes,
Xavier
