### ISSUE TITLE
Obtained a lot of genomes with "?" 

### ISSUE THREAD

**Issue by OrsonMM** [xavierdidelot/ClonalFrameML#78]
Dear Xavier

I have a problem maybe you can help me. 

I used the commands using snps of 776 genomes :

1. raxmlHPC-PTHREADS -m GTRGAMMA -f a -p 01234 -x 01234  -# 300 -s snp_776_SE.fasta -T 15 -n out

2.  ClonalFrameML RAxML_bestTree.out snp_776_SE.fasta CF_out -ignore_incomplete_sites true

3.  cfml-maskrc.py --aln snp_776_SE.fasta --out mask_776.fasta CF_out --svg graph.svg

finally I tried to do a new tree using RaxML with the file mask_776.fasta (output of 3 step)

And I have the error that 6 genomes have a lot of  "?". 

I can check inside of my file and in 6 genomes  were completely replaced with "?"
for these reasoon is not possible run a new tree without recombination. 

What mean that a whole snp genome are now "?". Maybe is a whole recombination. 

I use the tool in other data set but I never see this problem. 

Please,

**Comment by xavierdidelot** [comment]
Dear OrsonMM,

The "?" signs would have been inserted by cfml-maskrc.py presumably because of recombination, although you would have to ask the authors of this script to be sure if this is the expected behaviour.

By the way, why would you want to remove recombination and build a new tree rather than use the tree directly output by ClonalFrameML? This tree should be better since it does not just remove recombined regions but rather accounts for recombination events on the branches where they happened.

Best wishes,
Xavier
