### ISSUE TITLE
Embranch em.txt is missing very short branches

### ISSUE THREAD

**Issue by TheG-Meister** [xavierdidelot/ClonalFrameML#82]
Hi there,

I have run CFML for a data set of 282 isolates using the embranch model with dispersion parameter 0.5. Both the input and output trees contained 563 nodes + tips, and therefore 562 branches. However, the resulting em.txt output only contains data for 463 of them.

I've performed some analysis in R, and it appears that the omitted branches are the hundred shortest. In the maximum likelihood tree, all have branch lengths of 1.041e-7 or shorter (though the next longest branch is 4.907e-7), and are drawn into the CFML tree with a branch length of exactly 1e-7.

Here is a zip file containing the em.txt, input tree, output tree and R table. The table is sorted by the input branch lengths.
[CFML issue.zip](https://github.com/xavierdidelot/ClonalFrameML/files/3505734/CFML.issue.zip)

Best regards,
Grant

**Comment by xavierdidelot** [comment]
Hi Grant,

I think these are branches in which not a single substitution is found, so that it would be superfluous to try and fit a the per-branch model implied by the embranch option. In other words, these branches are not included because there is nothing interesting to say about them.

Best wishes,
Xavier
