### ISSUE TITLE
cfml_results.R plot

### ISSUE THREAD

**Issue by Edison2021** [xavierdidelot/ClonalFrameML#86]
Hi Xavier
When plotting the recombination regions using cfml_results.R, the inter-nodes are also included. Any way to plot the branch only excluding inter-nodes?

Thanks
Edison

**Comment by xavierdidelot** [comment]
Dear Edison,

Yes indeed the internal nodes are included in order to show recombination events that occurred on internal branches. Why do you fin this to be a problem? If the internal nodes were simply removed, then there would be some recombination events not shown, possibly the most important ones, and the graphical representation would then be quite misleading. 

The only valid way of removing internal nodes would be to project on the terminal branches all the events that happened on the path from the root to the tip. So recombination events that occurred on internal branches would then be shown for all leaves that descend from this internal branch. Would you find this useful?

Best wishes,
Xavier

**Comment by xavierdidelot** [comment]
PS: if anybody thinks the idea in my second paragraph would be useful, let me know and I'll implement it, but personally I find it more useful to see on exactly which branch the recombination events were.

**Comment by megaptera-helvetiae** [comment]
Hi Xavier and Edison,

I think I am having a similar problem that is why I am re-opening this issue.

The R-script to plot the nice output pdf seems to cause a problem with the internal nodes. When I run the script line by line, it starts bugging at line 294 when plotting the vertical branches. 

 Error in arrows(hpos, vpos[1], hpos, vpos[2], len = 0, col = 1) : 
  cannot mix zero-length and non-zero-length coordinates 

I see that the values for the internal nodes are NAs. 

Would you mind having a look? It is not clear to me how to de-bug. Since you are more familiar with the R-script, I assumed you might see where the culprit is hiding.

Thank you!
Laetitia

[test_out_ClaCo.importation_status.txt](https://github.com/xavierdidelot/ClonalFrameML/files/4774395/test_out_ClaCo.importation_status.txt)
[test_out_ClaCo.labelled_tree.newick.txt](https://github.com/xavierdidelot/ClonalFrameML/files/4774397/test_out_ClaCo.labelled_tree.newick.txt)
[test_out_ClaCo.em.txt](https://github.com/xavierdidelot/ClonalFrameML/files/4774398/test_out_ClaCo.em.txt)
[test_out_ClaCo.position_cross_reference.txt](https://github.com/xavierdidelot/ClonalFrameML/files/4774399/test_out_ClaCo.position_cross_reference.txt)
[test_out_ClaCo.ML_sequence.fasta.txt](https://github.com/xavierdidelot/ClonalFrameML/files/4774409/test_out_ClaCo.ML_sequence.fasta.txt)

[NA.cfml.pdf](https://github.com/xavierdidelot/ClonalFrameML/files/4774400/NA.cfml.pdf)

**Comment by xavierdidelot** [comment]
Hi Laetitia,

Thanks for using ClonalFrameML!
The file that attached called test_out_ClaCo.labelled_tree.newick.txt does not look like a normal output from ClonalFrameML. Are you sure you did not edit it in some way?

Best wishes,
Xavier

**Comment by megaptera-helvetiae** [comment]
Hi Xavier,

ClonalFrameML is great fun to use!

I opened the tree file to look at it in FigTree and then exported it as newick file.

Here is the original after running ClonalFrameML again:
[runAgain_out_ClaCo.labelled_tree.newick.txt](https://github.com/xavierdidelot/ClonalFrameML/files/4779476/runAgain_out_ClaCo.labelled_tree.newick.txt)

Laetitia

**Comment by xavierdidelot** [comment]
When I try with this file it works fine on my side, does it work on yours?
It seems that opening and saving the file in FigTree removes the names of the internal nodes that are needed to build the ClonalFrameML figure, so it is best to always use the unedited output file.

**Comment by megaptera-helvetiae** [comment]
Yes, it is working!

Thank you so much.

Looking at the figure now. It is awesome. White and dark blue bars are clear but what are all the light blue bars in the taxa on the top half of the phylogeny?

**Comment by xavierdidelot** [comment]
Great! The dark blue regions represent recombination. Sites that are non polymorphic for a given branch are shown in light blue. Polymorphic sites are shown in a color indicating their level of homoplasy: white is no homoplasy and the range from yellow to red is increasing degrees of homoplasy. You may want to remove this by editing the R script cf line 308.
