### ISSUE TITLE
Core and non-core sites

### ISSUE THREAD

**Issue by DarioUH-HI-2019** [xavierdidelot/ClonalFrameML#90]
Dear Dr. Xavier Didelot. I was working with the example file of ClonalFrameML available in the User manual and I was wondering what program did you use to generate the core and non-core sites? since the core-sites file is used to generate the graphic with R. 

Another question that I would like to ask you, is in regard to the xmfa file. Using my own data, I already extracted the core-genome. However, I notice that in the alignment there is a "=" to separate the sequences. I guess I have to delete these = and generate a concatenated core alignment since the PhyML tree was generated using a concatenated alignment. Am I correct?

Thank you so much beforehand. I wish you an excellent day

**Comment by tseemann** [comment]
My software snippy is often used to generate input for CLonalFrameML or Gubbins:
https://github.com/tseemann/snippy#core-snp-phylogeny

**Comment by xavierdidelot** [comment]
You can tell ClonalFrameML to ignore non-core sites using the option ignore_user_sites, but unless there are really a lot of these sites it would not make much difference to keep them in the analysis. This is because non-core sites will contain a lot of gaps that will be imputed in the first step of the algorithm and therefore not result in especially many substitutions. 

If you have already extracted the core-genome as a xmfa file it is best to run ClonalFrameML on the xmfa file itself, so that blocks are not assumed to be next to each other which affects the reconstruction of recombination events. This is true even if you had to use a concatenation to run phyml.

But the recommended approach is to use as input a fasta alignment of SNPs against a reference genome, which can be produced for example using Torsten's snippy.
