### ISSUE TITLE
ClonalFrameML for multi-lineage comparisons?

### ISSUE THREAD

**Issue by cizydorczyk** [xavierdidelot/ClonalFrameML#91]
I was wondering what the effect of running ClonalFrameML would be on a dataset consisting of multiple lineages (i.e. MLST sequence types), and whether such an analysis would make sense in the first place? I ask because I am interested in identifying recombinant regions in a dataset consisting of ~12 MLST STs  (~50 isolates total), yet within an ST there are too few isolates for meaningful phylogenetic inference (often < 4) and to run ClonalFrameML per ST.

From my understanding, the ClonalFrameML model looks primarily for recombination from an external source, and not one internal to the population being studied. As per the ClonalFrameML paper as I understand it, the main result is that R/θ may be underestimated.

I imagine that any recombination between MLST lineages would still be readily detected, as it is more likely to introduce a higher number of polymorphisms, but that within-lineage (ST) recombination would be underestimated. But would adding further distinct lineages (STs) change which regions are identified as recombinant in the original set? And if so, why might that occur, based on the ClonalFrameML model?

I am thinking of simulating this myself -- asking how adding subsequent isolates/lineages (somewhat related to asking what the effect of sample size is as per #69) affects which regions are identified as recombinant -- but wanted to ask if there is already a theoretical answer to this question that I am currently missing before undertaking such an analysis!

Any help in understanding is greatly appreciated!!

Thank you,
Conrad

**Comment by xavierdidelot** [comment]
Dear Conrad,

If a dataset has clearly separate lineages (for example two STs separately by a long branch) then I would recommend running ClonalFrameML on each lineage separately. This is because as you mentioned ClonalFrame models recombination from external sources, and so by splitting the lineages we have a better chance to detect and correctly reconstruct recombination events that occurred between the lineages. However, if you have only a handful of isolates in some lineages then this approach may not be feasible. So the user needs to find the correct balance between dividing into too few or too many lineages. I have never done simulations to test exactly what is the optimum, and it could be interesting to do this. For most datasets though there is no obvious way to divide the population (ie no unexpectedly long branches separating lineages), and in this case it is probably best not to divide the dataset. 

Best wishes,
Xavier

**Comment by nbawe** [comment]
What does it mean? - “... meaningful phylogenetic inference (often < 4)...”

What parameter is <4 ?

**Comment by cizydorczyk** [comment]
Thank you Xavier for your response -- that helps clear it up.

@nbawe when I mentioned "< 4", I was referring to the number of isolates (samples) I had within a given MLST sequence type (ST).

**Comment by nbawe** [comment]
@cizydorczyk thank you
