### ISSUE TITLE
Can imports be long enough to cover multiple loci?

### ISSUE THREAD

**Issue by goshng** [xavierdidelot/ClonalFrameML#98]
I am trying to use ".importation_status.txt" output from CFML to see what genes are affected by recombination. From the issues in this github, I found out that CFML concatenates multiple loci sequences with 1000 bp in between two consecutive loci. So, I concatenated sequences from a genome and inserted 1000 bp with meaningless characters, say 'X', and extracted subsequences using information in ".importation_status.txt" file. I expected that the subsequences would have sequences in the xmfa alignment that I used with CFML, but they contained the meaningless characters, which indicated that recombination imports might range over multiple loci.

I am trying to describe what I did so that I could explain my question: can imports be long enough to cover multiple loci?

Thank you!

**Comment by xavierdidelot** [comment]
Hi Sang Chul,

I think I understand what you are doing. I would expect that you often see the meaningless characters at the beginning or end of imports, and you can just prune these when they happen. This would happen since the recombination events are not expected to start or end exactly where the sequences in the xmfa file start or end. It is a bit more surprising if you see recombination events stretching over a whole "buffer" of 1000bp of meaningless characters. Presumably this does not happen too often, in which case you could just split this as two events for the two genes before and after the buffer. 

Best wishes,
Xavier

**Comment by goshng** [comment]
Thank you for the prompt reply with the recommendation. I am analyzing African swine fever virus genomes (genome size being about 180 kb long) with ClonalFrameML to detect genes under recombination. It looks like that some internal branches have such cases of stretching over the whole buffer of 1000 bp. It may have something to do with short genome sizes, which might lead to smaller locus lengths. The following is the summary of one of my dataset, CFML analysis of which produced a few cases of such imports stretching over multiple loci.
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.
  513.0   940.2  1605.0  2484.3  3243.0 10266.0

Thank you again for developing another good method.

**Comment by xavierdidelot** [comment]
Thanks. How many genes do you have in the xmfa file, and what is their average length?

**Comment by goshng** [comment]
I guess what meant was the number of alignments in the xmfa file. The xmfa file has 56 alignments and the average length was 2484 bp.

**Comment by xavierdidelot** [comment]
Ok, that's a nice dataset. Is there any possibility to align the genomes in a single block, maybe using reference-based mapping? ClonalFrameML works better with this type of input. Otherwise you could use what you are currently doing and simply split the recombination that span over buffers.

**Comment by goshng** [comment]
I used progressiveMauve to align the 39 African swine fever virus genomes that produced an xmfa file, which was processed by stripSubsetLCBs, a part of Mauve package, to create the xmfa file for a core alignment with minimum 500 bp. So, it is not easy for me quickly to get such a single block alignment with my current approach. Do you happen to know any procedure that convert a multi-locus xmfa file to such a single block with a reference given? I guess that one could do that but it take a while. I select a reference genome from the 39 genomes, and map each alignment in the xmfa file to the reference genome. Then, would all of the not-mapped parts of the reference genome be filled with gaps?

I am trying to explain how I could do a reference-based mapping with the xmfa file that I have. Could that be what you meant for "a single block"?

Another question is why ClonalFrameML does better in such a single block. One possibility that I think of is that the single block have real "buffer" rather artificial "buffers" of 1000 bp, which might make ClonalFrameML work better.

Thank you for your reply.

P.S. I know it is not appropriate to ask a different topic here. But, a simple question: the coordinate system in ".importation_status.txt" is 1-based or 0-based. I assume it uses 1-based genomic position. ClonalFrameML has the option:
-chromosome_name
to produce ".importation_status.txt" in BED format. I guess that BED format uses 0-based coordinate: i.e., the first base on the chromosome is numbered 0. Then, the BED format output would have different values than the usual ".importation_status.txt" file. I am a little confused by that.
Maybe, I should have opened an new issue with that.

**Comment by xavierdidelot** [comment]
Yes indeed it would probably be better to try and paste your xmfa file into a single fasta file so that the blocks are at the correct position relative to one another, rather than using 1000bp buffers. I don't know of a software to do this, but this should not be too difficult to do if you know where the blocks are in a full genome. You could then use the ClonalFrameML option -ignore_user_sites to ignore the sites that are not actual sequences. If one of the genomes used in your Mauve alignment was complete, then you could use the Mauve information on location of the blocks in that genome. 

The importation_status.txt file uses 1-based indexing of sites.

**Comment by goshng** [comment]
Thank you!
